### ISSUE TITLE
git branch illegible

### ISSUE THREAD

**Issue by ghost** [nshntarora/sublimify#1]
your ui is great, I've been using it for a few days now
however, in the ui that you forked off of, the git branch in the bottom right is legible, and in sublimify it is not. see the attached photos to clarify what I mean. can you please update your repo? I would really like to continue using this! thanks!

![atom dark](https://cloud.githubusercontent.com/assets/13712320/17609791/ca94275c-5ffd-11e6-9537-8f88bb316d69.png)
![sublimify](https://cloud.githubusercontent.com/assets/13712320/17609792/ca981ace-5ffd-11e6-8b77-1fb6402f681f.png)

**Comment by nshntarora** [comment]
Hey @tripscripts 

Thanks a lot. Glad you like it.

Fixed the issue :smile:
