### ISSUE TITLE
quick navigate styles are broken

### ISSUE THREAD

**Issue by maksad** [nshntarora/sublimify#2]
pressing `cmt+t` or `cmd+p` and typing for example install shows:

![screen shot 2016-08-15 at 15 25 57](https://cloud.githubusercontent.com/assets/4527650/17664454/d1327c4c-62fc-11e6-9727-7d8adb682433.png)

I tried with `Monokai`, `atom dark.light` and etc the same issue

**Comment by nshntarora** [comment]
Hey @maksad 

The issue was with the list-group styles. Fixed it in the latest commit.

**Comment by maksad** [comment]
Amazing. Thanks
It deserves a ⭐  
Ps. Great Job :)
